/**
 * [description]
 */
export enum ErrorTypeEnum {
  /*
   * GENERAL
   */
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  INPUT_DATA_ERROR = 'INPUT_DATA_ERROR',
  NOT_FOUND_ERROR = 'NOT_FOUND_ERROR',
  INPUT_FILE_ERROR = 'INPUT_FILE_ERROR',
  INPUT_FILE_EMPTY_ERROR = 'INPUT_FILE_EMPTY_ERROR',
}
